In [44]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [8]:
def minimum(list):
    minValue=list[0]
    for x in list:
        if(x<minValue):
            minValue=x
    return minValue

In [9]:
def maximum(list):
    maxValue=list[0]
    for x in list:
        if(x>maxValue):
            maxValue=x
    return maxValue

In [10]:
def mean(list):
    total = 0
    for x in list:
        total = total + x
    meanValue=total/len(list)
    return meanValue

In [11]:
def median(lst):
    lst.sort()
    if len(lst)%2==0:
        return mean([lst[int(len(lst)/2)],lst[int(len(lst)/2)+1]])
    else:
        return lst[int(len(lst)/2)]

In [12]:
def stdev(list):
    mean_val=mean(list)
    total_difs=0
    for x in list:
        diff=x-mean_val
        difsq=abs(diff)**2
        total_difs=total_difs+difsq
    return (total_difs/len(list))**(1/2)

In [24]:
#get temps as csv
temperatures = pd.read_csv('temperatures.csv')

### 1) What were the daily high and low temperatures on the day you were born?

In [86]:
birthday_mask=(temperatures['year']==1995) & (temperatures['month']==12) & (temperatures['day']==13)
birthday_table=temperatures[birthday_mask]
print("Min temp for Judson's birthday: ",birthday_table['tmin'].values[0])
print("Max temp for Judson's birthday: ",birthday_table['tmax'].values[0])

Min temp for Judson's birthday:  19.0
Max temp for Judson's birthday:  28.0

### 2) What’s the hottest temperature on record for each month of the year (i.e. the hottest day in January any time in the last 60 years, the hottest day in February, etc.)?

In [79]:
year_mask=(temperatures['year']>temperatures['year'].max()-60)
year_table=temperatures[year_mask]
for i in range(1,13):
    month_mask=(year_table['month']==i)
    month_table=year_table[month_mask]
    print("Max temp for month ",i,": ",maximum(month_table['tmax'].tolist()))

Max temp for month  1 :  73.0
Max temp for month  2 :  74.0
Max temp for month  3 :  86.0
Max temp for month  4 :  95.0
Max temp for month  5 :  97.0
Max temp for month  6 :  100.0
Max temp for month  7 :  104.0
Max temp for month  8 :  101.0
Max temp for month  9 :  98.0
Max temp for month  10 :  89.0
Max temp for month  11 :  81.0
Max temp for month  12 :  73.0

### 3) For each day of the year, print the coldest it’s been on that day and the year that record was set

In [112]:
for m in range(1,13):
    for d in range(1,32):
        try:
            #get temp
            day_mask=(temperatures['month']==m) & (temperatures['day']==d)
            day_table=temperatures[day_mask]
            min_temp=minimum(day_table['tmin'].tolist())
            #get year
            year_mask=(day_table['tmin']==min_temp)
            year_table=day_table[year_mask]
            rec_year=year_table['year'].values[0]
            print("Min temp for ",m,"/",d,": ",min_temp,", set in ", rec_year)
        except:
            pass

Min temp for  1 / 1 :  6.0 , set in  2018
Min temp for  1 / 2 :  7.0 , set in  1968
Min temp for  1 / 3 :  11.0 , set in  2014
Min temp for  1 / 4 :  7.0 , set in  1981
Min temp for  1 / 5 :  10.0 , set in  1988
Min temp for  1 / 6 :  7.0 , set in  2018
Min temp for  1 / 7 :  4.0 , set in  2014
Min temp for  1 / 8 :  2.0 , set in  1970
Min temp for  1 / 9 :  1.0 , set in  1970
Min temp for  1 / 10 :  4.0 , set in  1982
Min temp for  1 / 11 :  1.0 , set in  1982
Min temp for  1 / 12 :  1.0 , set in  1981
Min temp for  1 / 13 :  0.0 , set in  1981
Min temp for  1 / 14 :  5.0 , set in  1954
Min temp for  1 / 15 :  2.0 , set in  1964
Min temp for  1 / 16 :  0.0 , set in  1977
Min temp for  1 / 17 :  -7.0 , set in  1982
Min temp for  1 / 18 :  -4.0 , set in  1982
Min temp for  1 / 19 :  -5.0 , set in  1994
Min temp for  1 / 20 :  -3.0 , set in  1984
Min temp for  1 / 21 :  -6.0 , set in  1985
Min temp for  1 / 22 :  -7.0 , set in  1984
Min temp for  1 / 23 :  3.0 , set in  1961
Min temp for  1 / 24 :  1.0 , set in  1963
Min temp for  1 / 25 :  -2.0 , set in  1963
Min temp for  1 / 26 :  4.0 , set in  1961
Min temp for  1 / 27 :  7.0 , set in  1987
Min temp for  1 / 28 :  3.0 , set in  1961
Min temp for  1 / 29 :  -5.0 , set in  1963
Min temp for  1 / 30 :  8.0 , set in  1948
Min temp for  1 / 31 :  3.0 , set in  1948
Min temp for  2 / 1 :  5.0 , set in  1961
Min temp for  2 / 2 :  -4.0 , set in  1961
Min temp for  2 / 3 :  5.0 , set in  1955
Min temp for  2 / 4 :  6.0 , set in  1965
Min temp for  2 / 5 :  3.0 , set in  1996
Min temp for  2 / 6 :  4.0 , set in  1966
Min temp for  2 / 7 :  8.0 , set in  1977
Min temp for  2 / 8 :  3.0 , set in  1963
Min temp for  2 / 9 :  4.0 , set in  1967
Min temp for  2 / 10 :  -1.0 , set in  1979
Min temp for  2 / 11 :  -2.0 , set in  1979
Min temp for  2 / 12 :  2.0 , set in  1979
Min temp for  2 / 13 :  3.0 , set in  1983
Min temp for  2 / 14 :  2.0 , set in  1979
Min temp for  2 / 15 :  9.0 , set in  1987
Min temp for  2 / 16 :  3.0 , set in  2015
Min temp for  2 / 17 :  2.0 , set in  1979
Min temp for  2 / 18 :  0.0 , set in  1979
Min temp for  2 / 19 :  8.0 , set in  2015
Min temp for  2 / 20 :  1.0 , set in  1979
Min temp for  2 / 21 :  6.0 , set in  1968
Min temp for  2 / 22 :  7.0 , set in  1963
Min temp for  2 / 23 :  6.0 , set in  1963
Min temp for  2 / 24 :  7.0 , set in  2015
Min temp for  2 / 25 :  13.0 , set in  1967
Min temp for  2 / 26 :  10.0 , set in  1970
Min temp for  2 / 27 :  7.0 , set in  1963
Min temp for  2 / 28 :  10.0 , set in  2014
Min temp for  2 / 29 :  13.0 , set in  1980
Min temp for  3 / 1 :  9.0 , set in  1980
Min temp for  3 / 2 :  12.0 , set in  1962
Min temp for  3 / 3 :  13.0 , set in  1950
Min temp for  3 / 4 :  10.0 , set in  1962
Min temp for  3 / 5 :  8.0 , set in  1978
Min temp for  3 / 6 :  10.0 , set in  1978
Min temp for  3 / 7 :  9.0 , set in  1960
Min temp for  3 / 8 :  12.0 , set in  1986
Min temp for  3 / 9 :  12.0 , set in  1960
Min temp for  3 / 10 :  7.0 , set in  1984
Min temp for  3 / 11 :  12.0 , set in  1960
Min temp for  3 / 12 :  14.0 , set in  1984
Min temp for  3 / 13 :  19.0 , set in  1960
Min temp for  3 / 14 :  19.0 , set in  1993
Min temp for  3 / 15 :  11.0 , set in  1993
Min temp for  3 / 16 :  17.0 , set in  1979
Min temp for  3 / 17 :  18.0 , set in  1967
Min temp for  3 / 18 :  15.0 , set in  1967
Min temp for  3 / 19 :  11.0 , set in  1967
Min temp for  3 / 20 :  16.0 , set in  1965
Min temp for  3 / 21 :  12.0 , set in  1965
Min temp for  3 / 22 :  19.0 , set in  1988
Min temp for  3 / 23 :  23.0 , set in  1959
Min temp for  3 / 24 :  23.0 , set in  1992
Min temp for  3 / 25 :  21.0 , set in  1956
Min temp for  3 / 26 :  21.0 , set in  1960
Min temp for  3 / 27 :  23.0 , set in  1975
Min temp for  3 / 28 :  20.0 , set in  1966
Min temp for  3 / 29 :  23.0 , set in  1959
Min temp for  3 / 30 :  25.0 , set in  1970
Min temp for  3 / 31 :  22.0 , set in  1964
Min temp for  4 / 1 :  24.0 , set in  1969
Min temp for  4 / 2 :  25.0 , set in  1964
Min temp for  4 / 3 :  28.0 , set in  1954
Min temp for  4 / 4 :  26.0 , set in  1954
Min temp for  4 / 5 :  26.0 , set in  1965
Min temp for  4 / 6 :  24.0 , set in  1982
Min temp for  4 / 7 :  19.0 , set in  1982
Min temp for  4 / 8 :  23.0 , set in  1982
Min temp for  4 / 9 :  26.0 , set in  1977
Min temp for  4 / 10 :  22.0 , set in  1985
Min temp for  4 / 11 :  28.0 , set in  1966
Min temp for  4 / 12 :  29.0 , set in  1967
Min temp for  4 / 13 :  28.0 , set in  1990
Min temp for  4 / 14 :  24.0 , set in  1950
Min temp for  4 / 15 :  31.0 , set in  1957
Min temp for  4 / 16 :  31.0 , set in  2014
Min temp for  4 / 17 :  27.0 , set in  1962
Min temp for  4 / 18 :  32.0 , set in  1983
Min temp for  4 / 19 :  32.0 , set in  1983
Min temp for  4 / 20 :  32.0 , set in  1983
Min temp for  4 / 21 :  32.0 , set in  1956
Min temp for  4 / 22 :  32.0 , set in  1988
Min temp for  4 / 23 :  33.0 , set in  1982
Min temp for  4 / 24 :  34.0 , set in  1989
Min temp for  4 / 25 :  33.0 , set in  1956
Min temp for  4 / 26 :  35.0 , set in  1967
Min temp for  4 / 27 :  36.0 , set in  1967
Min temp for  4 / 28 :  35.0 , set in  1966
Min temp for  4 / 29 :  36.0 , set in  1948
Min temp for  4 / 30 :  38.0 , set in  1961
Min temp for  5 / 1 :  34.0 , set in  1978
Min temp for  5 / 2 :  35.0 , set in  1960
Min temp for  5 / 3 :  35.0 , set in  1966
Min temp for  5 / 4 :  35.0 , set in  1957
Min temp for  5 / 5 :  33.0 , set in  1966
Min temp for  5 / 6 :  42.0 , set in  1954
Min temp for  5 / 7 :  35.0 , set in  1970
Min temp for  5 / 8 :  39.0 , set in  1974
Min temp for  5 / 9 :  38.0 , set in  1966
Min temp for  5 / 10 :  33.0 , set in  1966
Min temp for  5 / 11 :  28.0 , set in  1966
Min temp for  5 / 12 :  37.0 , set in  1962
Min temp for  5 / 13 :  37.0 , set in  1967
Min temp for  5 / 14 :  40.0 , set in  1996
Min temp for  5 / 15 :  39.0 , set in  1966
Min temp for  5 / 16 :  40.0 , set in  1959
Min temp for  5 / 17 :  37.0 , set in  1956
Min temp for  5 / 18 :  41.0 , set in  1973
Min temp for  5 / 19 :  42.0 , set in  1973
Min temp for  5 / 20 :  43.0 , set in  2002
Min temp for  5 / 21 :  41.0 , set in  2002
Min temp for  5 / 22 :  44.0 , set in  2002
Min temp for  5 / 23 :  41.0 , set in  1961
Min temp for  5 / 24 :  40.0 , set in  1963
Min temp for  5 / 25 :  40.0 , set in  1963
Min temp for  5 / 26 :  43.0 , set in  1961
Min temp for  5 / 27 :  42.0 , set in  1961
Min temp for  5 / 28 :  41.0 , set in  1961
Min temp for  5 / 29 :  45.0 , set in  1949
Min temp for  5 / 30 :  41.0 , set in  1961
Min temp for  5 / 31 :  42.0 , set in  1965
Min temp for  6 / 1 :  44.0 , set in  1967
Min temp for  6 / 2 :  47.0 , set in  1966
Min temp for  6 / 3 :  48.0 , set in  1966
Min temp for  6 / 4 :  47.0 , set in  1977
Min temp for  6 / 5 :  48.0 , set in  1990
Min temp for  6 / 6 :  48.0 , set in  1948
Min temp for  6 / 7 :  47.0 , set in  1958
Min temp for  6 / 8 :  44.0 , set in  1977
Min temp for  6 / 9 :  44.0 , set in  1957
Min temp for  6 / 10 :  47.0 , set in  1988
Min temp for  6 / 11 :  44.0 , set in  1972
Min temp for  6 / 12 :  48.0 , set in  1979
Min temp for  6 / 13 :  50.0 , set in  1979
Min temp for  6 / 14 :  48.0 , set in  1965
Min temp for  6 / 15 :  49.0 , set in  1978
Min temp for  6 / 16 :  49.0 , set in  1963
Min temp for  6 / 17 :  44.0 , set in  1964
Min temp for  6 / 18 :  48.0 , set in  1950
Min temp for  6 / 19 :  54.0 , set in  1980
Min temp for  6 / 20 :  51.0 , set in  1956
Min temp for  6 / 21 :  48.0 , set in  1968
Min temp for  6 / 22 :  48.0 , set in  1963
Min temp for  6 / 23 :  47.0 , set in  1963
Min temp for  6 / 24 :  54.0 , set in  1958
Min temp for  6 / 25 :  52.0 , set in  1979
Min temp for  6 / 26 :  51.0 , set in  1960
Min temp for  6 / 27 :  50.0 , set in  1965
Min temp for  6 / 28 :  54.0 , set in  1961
Min temp for  6 / 29 :  56.0 , set in  1970
Min temp for  6 / 30 :  52.0 , set in  1988
Min temp for  7 / 1 :  52.0 , set in  1988
Min temp for  7 / 2 :  52.0 , set in  1965
Min temp for  7 / 3 :  54.0 , set in  1957
Min temp for  7 / 4 :  52.0 , set in  1986
Min temp for  7 / 5 :  55.0 , set in  1963
Min temp for  7 / 6 :  52.0 , set in  1960
Min temp for  7 / 7 :  55.0 , set in  1968
Min temp for  7 / 8 :  53.0 , set in  1960
Min temp for  7 / 9 :  53.0 , set in  1963
Min temp for  7 / 10 :  53.0 , set in  1963
Min temp for  7 / 11 :  55.0 , set in  1963
Min temp for  7 / 12 :  55.0 , set in  1999
Min temp for  7 / 13 :  58.0 , set in  1980
Min temp for  7 / 14 :  61.0 , set in  1962
Min temp for  7 / 15 :  59.0 , set in  1999
Min temp for  7 / 16 :  56.0 , set in  1960
Min temp for  7 / 17 :  58.0 , set in  1966
Min temp for  7 / 18 :  57.0 , set in  1976
Min temp for  7 / 19 :  58.0 , set in  1962
Min temp for  7 / 20 :  59.0 , set in  1965
Min temp for  7 / 21 :  51.0 , set in  1966
Min temp for  7 / 22 :  57.0 , set in  1966
Min temp for  7 / 23 :  58.0 , set in  1950
Min temp for  7 / 24 :  57.0 , set in  1985
Min temp for  7 / 25 :  56.0 , set in  1953
Min temp for  7 / 26 :  57.0 , set in  1976
Min temp for  7 / 27 :  53.0 , set in  1962
Min temp for  7 / 28 :  53.0 , set in  1962
Min temp for  7 / 29 :  60.0 , set in  1984
Min temp for  7 / 30 :  58.0 , set in  1981
Min temp for  7 / 31 :  58.0 , set in  1956
Min temp for  8 / 1 :  56.0 , set in  1964
Min temp for  8 / 2 :  59.0 , set in  1976
Min temp for  8 / 3 :  56.0 , set in  1959
Min temp for  8 / 4 :  52.0 , set in  1965
Min temp for  8 / 5 :  52.0 , set in  1951
Min temp for  8 / 6 :  53.0 , set in  1957
Min temp for  8 / 7 :  54.0 , set in  1964
Min temp for  8 / 8 :  55.0 , set in  1989
Min temp for  8 / 9 :  54.0 , set in  1964
Min temp for  8 / 10 :  54.0 , set in  1964
Min temp for  8 / 11 :  55.0 , set in  1972
Min temp for  8 / 12 :  53.0 , set in  1962
Min temp for  8 / 13 :  55.0 , set in  1964
Min temp for  8 / 14 :  50.0 , set in  1964
Min temp for  8 / 15 :  50.0 , set in  1963
Min temp for  8 / 16 :  53.0 , set in  1964
Min temp for  8 / 17 :  50.0 , set in  1979
Min temp for  8 / 18 :  52.0 , set in  1961
Min temp for  8 / 19 :  51.0 , set in  1963
Min temp for  8 / 20 :  52.0 , set in  1949
Min temp for  8 / 21 :  54.0 , set in  1949
Min temp for  8 / 22 :  53.0 , set in  1956
Min temp for  8 / 23 :  53.0 , set in  1952
Min temp for  8 / 24 :  50.0 , set in  1957
Min temp for  8 / 25 :  47.0 , set in  1963
Min temp for  8 / 26 :  51.0 , set in  1963
Min temp for  8 / 27 :  51.0 , set in  1963
Min temp for  8 / 28 :  49.0 , set in  1986
Min temp for  8 / 29 :  44.0 , set in  1986
Min temp for  8 / 30 :  47.0 , set in  1986
Min temp for  8 / 31 :  45.0 , set in  1965
Min temp for  9 / 1 :  49.0 , set in  1963
Min temp for  9 / 2 :  47.0 , set in  1963
Min temp for  9 / 3 :  51.0 , set in  1958
Min temp for  9 / 4 :  52.0 , set in  1997
Min temp for  9 / 5 :  53.0 , set in  1994
Min temp for  9 / 6 :  48.0 , set in  1962
Min temp for  9 / 7 :  47.0 , set in  1962
Min temp for  9 / 8 :  45.0 , set in  1962
Min temp for  9 / 9 :  49.0 , set in  1956
Min temp for  9 / 10 :  45.0 , set in  1956
Min temp for  9 / 11 :  47.0 , set in  1976
Min temp for  9 / 12 :  47.0 , set in  1958
Min temp for  9 / 13 :  44.0 , set in  1958
Min temp for  9 / 14 :  44.0 , set in  1975
Min temp for  9 / 15 :  46.0 , set in  1975
Min temp for  9 / 16 :  45.0 , set in  1984
Min temp for  9 / 17 :  44.0 , set in  1959
Min temp for  9 / 18 :  42.0 , set in  1959
Min temp for  9 / 19 :  43.0 , set in  1959
Min temp for  9 / 20 :  45.0 , set in  1956
Min temp for  9 / 21 :  38.0 , set in  1956
Min temp for  9 / 22 :  39.0 , set in  1962
Min temp for  9 / 23 :  40.0 , set in  1983
Min temp for  9 / 24 :  40.0 , set in  1963
Min temp for  9 / 25 :  35.0 , set in  1963
Min temp for  9 / 26 :  38.0 , set in  1963
Min temp for  9 / 27 :  38.0 , set in  1957
Min temp for  9 / 28 :  37.0 , set in  1957
Min temp for  9 / 29 :  40.0 , set in  1951
Min temp for  9 / 30 :  39.0 , set in  1961
Min temp for  10 / 1 :  41.0 , set in  1963
Min temp for  10 / 2 :  39.0 , set in  1966
Min temp for  10 / 3 :  33.0 , set in  1974
Min temp for  10 / 4 :  34.0 , set in  1974
Min temp for  10 / 5 :  31.0 , set in  1961
Min temp for  10 / 6 :  32.0 , set in  1965
Min temp for  10 / 7 :  37.0 , set in  1954
Min temp for  10 / 8 :  32.0 , set in  1964
Min temp for  10 / 9 :  35.0 , set in  1978
Min temp for  10 / 10 :  33.0 , set in  1979
Min temp for  10 / 11 :  28.0 , set in  1964
Min temp for  10 / 12 :  28.0 , set in  1964
Min temp for  10 / 13 :  32.0 , set in  1988
Min temp for  10 / 14 :  30.0 , set in  1988
Min temp for  10 / 15 :  35.0 , set in  1987
Min temp for  10 / 16 :  38.0 , set in  1961
Min temp for  10 / 17 :  34.0 , set in  1961
Min temp for  10 / 18 :  32.0 , set in  1982
Min temp for  10 / 19 :  29.0 , set in  1976
Min temp for  10 / 20 :  27.0 , set in  1974
Min temp for  10 / 21 :  28.0 , set in  1952
Min temp for  10 / 22 :  31.0 , set in  1974
Min temp for  10 / 23 :  31.0 , set in  1969
Min temp for  10 / 24 :  25.0 , set in  1969
Min temp for  10 / 25 :  25.0 , set in  1962
Min temp for  10 / 26 :  29.0 , set in  1960
Min temp for  10 / 27 :  30.0 , set in  1976
Min temp for  10 / 28 :  28.0 , set in  1976
Min temp for  10 / 29 :  30.0 , set in  1965
Min temp for  10 / 30 :  27.0 , set in  1962
Min temp for  10 / 31 :  26.0 , set in  1966
Min temp for  11 / 1 :  30.0 , set in  1968
Min temp for  11 / 2 :  27.0 , set in  1976
Min temp for  11 / 3 :  28.0 , set in  1951
Min temp for  11 / 4 :  26.0 , set in  1951
Min temp for  11 / 5 :  27.0 , set in  1952
Min temp for  11 / 6 :  26.0 , set in  1962
Min temp for  11 / 7 :  20.0 , set in  1962
Min temp for  11 / 8 :  25.0 , set in  1960
Min temp for  11 / 9 :  23.0 , set in  1976
Min temp for  11 / 10 :  23.0 , set in  1961
Min temp for  11 / 11 :  21.0 , set in  1961
Min temp for  11 / 12 :  26.0 , set in  1960
Min temp for  11 / 13 :  24.0 , set in  1996
Min temp for  11 / 14 :  19.0 , set in  1986
Min temp for  11 / 15 :  24.0 , set in  1967
Min temp for  11 / 16 :  22.0 , set in  1967
Min temp for  11 / 17 :  25.0 , set in  1980
Min temp for  11 / 18 :  21.0 , set in  1959
Min temp for  11 / 19 :  20.0 , set in  2014

Min temp for  11 / 20 :  21.0 , set in  1984
Min temp for  11 / 21 :  21.0 , set in  1987
Min temp for  11 / 22 :  17.0 , set in  1964
Min temp for  11 / 23 :  19.0 , set in  1964
Min temp for  11 / 24 :  19.0 , set in  1970
Min temp for  11 / 25 :  20.0 , set in  2013
Min temp for  11 / 26 :  21.0 , set in  1950
Min temp for  11 / 27 :  18.0 , set in  1974
Min temp for  11 / 28 :  19.0 , set in  1951
Min temp for  11 / 29 :  15.0 , set in  1955
Min temp for  11 / 30 :  15.0 , set in  1976
Min temp for  12 / 1 :  14.0 , set in  1976
Min temp for  12 / 2 :  17.0 , set in  1967
Min temp for  12 / 3 :  9.0 , set in  1976
Min temp for  12 / 4 :  12.0 , set in  1966
Min temp for  12 / 5 :  21.0 , set in  1966
Min temp for  12 / 6 :  20.0 , set in  1954
Min temp for  12 / 7 :  16.0 , set in  2002
Min temp for  12 / 8 :  17.0 , set in  1965
Min temp for  12 / 9 :  14.0 , set in  1960
Min temp for  12 / 10 :  12.0 , set in  1968
Min temp for  12 / 11 :  10.0 , set in  1968
Min temp for  12 / 12 :  8.0 , set in  1988
Min temp for  12 / 13 :  8.0 , set in  1960
Min temp for  12 / 14 :  10.0 , set in  1960
Min temp for  12 / 15 :  7.0 , set in  1960
Min temp for  12 / 16 :  12.0 , set in  1951
Min temp for  12 / 17 :  8.0 , set in  1951
Min temp for  12 / 18 :  10.0 , set in  1960
Min temp for  12 / 19 :  10.0 , set in  1960
Min temp for  12 / 20 :  9.0 , set in  1963
Min temp for  12 / 21 :  9.0 , set in  1955
Min temp for  12 / 22 :  6.0 , set in  1989
Min temp for  12 / 23 :  7.0 , set in  1989
Min temp for  12 / 24 :  3.0 , set in  1983
Min temp for  12 / 25 :  1.0 , set in  1980
Min temp for  12 / 26 :  3.0 , set in  1983
Min temp for  12 / 27 :  8.0 , set in  1989
Min temp for  12 / 28 :  9.0 , set in  1950
Min temp for  12 / 29 :  13.0 , set in  1977
Min temp for  12 / 30 :  4.0 , set in  1962
Min temp for  12 / 31 :  3.0 , set in  1962

### 4) What’s the earliest day of the year it’s safe to plant frost-sensitive garden plants?

In [20]:
def last_frost(year):
    idk=temperatures[(temperatures['year']==year)]
    mask=((idk['tmin']<33))
    print(mask)

In [113]:
last_frost(1957)

3288     True
3289     True
3290     True
3291     True
3292     True
3293     True
3294     True
3295     True
3296     True
3297     True
3298     True
3299     True
3300     True
3301     True
3302     True
3303     True
3304     True
3305     True
3306     True
3307     True
3308    False
3309    False
3310     True
3311     True
3312     True
3313     True
3314     True
3315     True
3316     True
3317     True
        ...
3623    False
3624     True
3625     True
3626     True
3627     True
3628    False
3629    False
3630    False
3631    False
3632     True
3633     True
3634     True
3635     True
3636     True
3637     True
3638     True
3639    False
3640    False
3641    False
3642    False
3643    False
3644    False
3645    False
3646     True
3647    False
3648    False
3649     True
3650    False
3651     True
3652     True
Name: tmin, Length: 365, dtype: bool

In [118]:
for m in range(1,13):
    for d in range(1,32):
        try:
            #get day mask
            day_mask=(temperatures['month']==m) & (temperatures['day']==d)
            day_table=temperatures[day_mask]
            #get row count of table
            total_days=len(day_table.index)
            print(total_days)
            min_temp=minimum(day_table['tmin'].tolist())
            #get year
            year_mask=(day_table['tmin']==min_temp)
            year_table=day_table[year_mask]
            rec_year=year_table['year'].values[0]
            #print("Min temp for ",m,"/",d,": ",min_temp,", set in ", rec_year)
        except:
            pass

71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
18
0
0
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
0
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
0
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
0
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
0
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70

In [119]:
len(temperatures.index)

25591